# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: job1
    steps:
    - script: echo build Job1 Hello, world!
      displayName: 'build script1 - Run a one-line script'

    - bash: echo $(Agent.JobStatus)
    - bash: echo $(Agent.Name)

    - script: |
        echo 'build script3 - this is a multiline
        sentence.'

  - job: job2
    steps:
    - script: echo script1 - his is Job2
      displayName: 'job2 script'

    - script: |
        echo Script2 - Add other tasks to build, test, and deploy your project.
      displayName: 'Run a multi-line script'

    - script: |
        echo 'script3 - this is a multiline
        sentence.'

- stage: test
  dependsOn: Build
  jobs:
  - job: job3
    displayName: testing - this is job3
    # dependsOn: job1
    steps:
    - script: echo testing - script1 - his is Job2
      displayName: 'testing - Run a one-line script'

    - script: |
        echo testing - Script2 - Add other tasks to build, test, and deploy your project.
      displayName: 'testing - Run a multi-line script'

    - bash: ls -R $(Build.ArtifactStagingDirectory)
    
    - script: |
        echo 'script3 - this is a multiline
        sentence.'

- stage: deploy
  dependsOn: Build
  jobs:
  - job: job1
    steps:
    - script: echo deploy - Job1 Hello, world!
      displayName: 'deploy - script1 - Run a one-line script'

    - script: |
        echo deploy - Add other tasks to build, test, and deploy your project.
      displayName: 'deploy - script2 - Run a multi-line script'

    - script: |
        echo 'deploy - script3 - this is a multiline
        sentence.'

  - job: job2
    steps:
    - script: echo deploy - script1 - his is Job2
      displayName: 'deploy - job2 script'

    - script: |
        echo deploy - Script2 - Add other tasks to build, test, and deploy your project.
      displayName: 'deploy - Run a multi-line script'

    - script: |
        echo 'deploy - script3 - this is a multiline
        sentence.'





# PodConfig:
#   port: 8080
#   retries: 3

# MyList:
# - description: this is my list
#   name: mark
#   age: 42
# - description: this is the second element
#   name: jim
#   age: 24

#this is sanother syntax to make a list
#MyList2: ['string 1', 'string 2', 'string 3']

# #beginining of a K8s YAML
# ApiVersion: v1 
# Kind: Pod
# #object 
# MetaData: 
#   Name: nginx	#property 
#   #property that is an object
#   Labels:
#     App: nginx	#property of the property 
# #another object 
# Spec:
#     #a list 
#   Containers:
#   - name: nginx –container
#     Image: nginx
#     #a list of one item 
#     Ports:
#     - containerPort: 80
#     VolumeMounts: 80
#     ColumeMounts:
#     - name: nginx-vol
#       MountPath: /usr/nginx/html
#     - name: otherThing
#       MountPath: /usr/otherthing/html 